name: mdlm
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - pytorch-cuda=12.1
  - cuda-nvcc=12.4.99
  - jupyter=1.0.0
  - pip=23.3.1
  # - cuda-toolkit=12.1  # flash bug
